Avr smart shooting
4322/2024_Robot pull request #23
Opened 2024-03-28 00:35 UTC by dKarangula

2024-03-28 20:13 UTC, zaydkhan4322 requested changes
please see targeting and rounding change

2024-03-28 20:13 UTC, zaydkhan4322 commented on src/main/java/frc/robot/commands/OuttakeManual/OuttakeManual.java
> +        if (outtakeLimelight.getTargetVisible()) {
this needs to check if we're seeing the correct tag, not just any target

2024-03-28 20:13 UTC, zaydkhan4322 commented on src/main/java/frc/robot/commands/OuttakeManual/OuttakeManual.java
> +          // Round to two decimals to reduce noise and have a stable shooting angle and flywheel speed
i'd round to 1 decimal, if not just a whole number. we can also consider into rounding by .2s or something (mult/divide by 5) if we want

2024-03-28 21:54 UTC, dKarangula commented on src/main/java/frc/robot/commands/OuttakeManual/OuttakeManual.java
> +          // Round to two decimals to reduce noise and have a stable shooting angle and flywheel speed
Is rounding to whole number or 1 decimal precise enough with units as meters? The farther we go from the speaker, the more accurate we need our shooting interpolation. Our current interpolation has multiple shots for 1 meter, and I'm not sure if rounding to 1 or 0 decimals is accurate enough.

2024-03-29 19:28 UTC, zaydkhan4322 approved these changes

2024-03-29 19:28 UTC, zaydkhan4322 commented on src/main/java/frc/robot/RobotContainer.java
> +                outtakeManual.setFiringSolution(Constants.FiringSolutions.DefaultSmartShooting);
this implementation is not what I was thinking of but it's fine

2024-03-29 19:28 UTC, zaydkhan4322 commented on src/main/java/frc/robot/RobotContainer.java
> +                outtakeManual.setFiringSolution(Constants.FiringSolutions.DefaultSmartShooting);
we can talk about it at the meeting if you want

2024-03-30 03:32 UTC, merged